### PR TITLE
refactor(layer) move not core leaflet layers to ui-leaflet-layers

### PR DESCRIPTION
**Pull request by elesdoar**
Move layers to [ui-leaflet-layers](https://github.com/elesdoar/ui-leaflet-layers)

### CODE REVIEW

**Comment by nmccready** [comment]
Cool this is a pretty core layer; the main fork should be in angular-ui.

**Comment by nmccready** [comment]
LGTM comment is something to consider.

**Comment by elesdoar** [comment]
@nmccready yes, it will be in angular-ui organization, when I finish test, examples and page.

**Comment by nmccready** [comment]
ok cool

**Pull request merged**
