### PR TITLE
fix(Markers): fix marker icon broken with latest Leaflet version (1.0)

### PR DESCRIPTION
**Pull request by ValentinH**
Leaflet now tries to auto-detect the path for the icons, but when using a base64 one, it breaks.
Thus, we need to force the imagePath to be ' '.
See this line in Leaflet source: https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Icon.Default.js#L36

Broken demo: http://jsfiddle.net/ar2bo629/
Fixed Demo: http://jsfiddle.net/f7bq9v6b/

### CODE REVIEW

**Comment by nmccready** [comment]
Anyway you can add a spec to assert this fix stay around?

**Comment by ValentinH** [comment]
Where should I add this test?

**Comment by nmccready** [comment]
@ValentinH https://github.com/angular-ui/ui-leaflet/blob/master/test/unit/services/leafletMarkersHelpersSpec.coffee

**Comment by ValentinH** [comment]
coffeescript? :cry: 
Is there a way where I can add tests in JS?

**Comment by nmccready** [comment]
> coffeescript? 😢 
> Is there a way where I can add tests in JS?

Seriously?, coffee is not much different then js, learn something new please. Otherwise add a `leafletMarkersHelpersSpec.js` file and ill convert it.

Coffee is not end of the world.

**Comment by elesdoar** [comment]
@ValentinH don't worry, You can write test in JS, but the new ES6 or ES7 looks like Coffee, but keep in coffee tests that are in coffee.

You could use http://js2.coffee/

**Comment by ValentinH** [comment]
Sorry, I was a bit trolling! :imp: 

But I think that having tests in Coffeescript is not really good to encourage new contributors to provide tests with their PR. Indeed, Coffeescript is not really use anymore today...

**Comment by ValentinH** [comment]
Don't worry, I will do it in coffee when I have some time.

**Comment by elesdoar** [comment]
I think that we have to go ES6 or ES7, but change all coffee specs requires a lot of  work.

@ValentinH  if you want you can translate this text to use JS but takes full advantages of ES6.

**Comment by ValentinH** [comment]
What do you mean by take full advantages?

**Comment by elesdoar** [comment]
@ValentinH 
Sorry for my bad explanation, it's so hard write in english. jaajaja... :cry: 

I mean that use arrow functions, template strings, classes, etc. Obviously where needed.
Please check http://es6-features.org

**Comment by nmccready** [comment]
I think the master branch already supports babel, so you can write ES6 there. I just prefer Coffee for specs cause its a whole lot less hassel for nested bracket and variable declaration. Plus I wrote a lot of the specs and to get them done fast I chose coffee. 

I still don't think ES6 is like coffee at all the arrow function means something much different in ES6 since you cant call apply or call to pass a different `this` on a function. Anyway, I could go on but ES6 is better for sure since it has structuring and destructuring.

**Comment by ValentinH** [comment]
Actually, I don't know how to test this. Currently, there is no test for marker/icon creations so I can't really understand from where to start. Thus, I wont' add test in this PR.

**Comment by elesdoar** [comment]
OK, I'll merge the change and I'll do this test.

Thanks @ValentinH

**Pull request merged**
