### PR TITLE
feat(travis): Added travis slack integration

### PR DESCRIPTION
**Pull request by jessertaylor**

### CODE REVIEW

**Comment by nmccready** [comment]
Not sure this should be plubic or not as the room is intended to be for contributing devs only. Right now it is invite only. For convenience factor I guess this could be valuable. In any case there should be a bullet about it being a closed/private room.

**Comment by jessertaylor** [comment]
Whilst I agree, this room only provides a feed of public information that is accessible on github, we never talk in that room.

**Comment by nmccready** [comment]
Ahh ok sounds good.

**Comment by nmccready** [comment]
My bad, I need more sleep. Some reason I thought this was adding slack to the readme.md.

**Comment by jessertaylor** [comment]
np

**Pull request merged**
